### ISSUE TITLE
Github link with wrong url 

### ISSUE THREAD

**Issue by jonnyforestGIS** [netuno-org/website#1]
Hi,
If you have an issue with your URL link check the image.
You have httdivs://github.com/netuno-org instead of https://github.com/netuno-org

https://github.com/netuno-org/website/blob/f5f09202ad6bf80321fd993d967191542d4d3a6b/website/src/base/Footer/index.js#L44

![minor_fix](https://user-images.githubusercontent.com/4480601/230038339-1c9b94dc-58dd-4779-849f-a4530613a0fc.png)

Cheers

**Comment by guilhermedpadua** [comment]
Hi, thanks for letting us know, the url has been corrected to the correct address!
